version: "3.7"

services:

  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sql_server
    ports:
      - 1435:1433
    environment:
      SA_PASSWORD: "Password01!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssqlsystem:/var/opt/mssql
      - mssqluser:/var/opt/sqlserver
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
    name: devnet_network

volumes:
  mssqlsystem:
    driver: local
  mssqluser:
    driver: local